server:
  port: 8002

spring:
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        username: nacos
        password: nacos
  application:
    name: sys_service
  datasource:
    url: jdbc:mysql://3l43723a04.wicp.vip:36336/my_blog?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: yhx5407582588
    driver-class-name: com.mysql.cj.jdbc.Driver

dubbo:
  protocol:
    port: -1
    name: dubbo
  scan:
    base-packages: com.yaohuaxiang.sys.serviceImpl
  registry:
    address: spring-cloud://localhost
  cloud:
    subscribed-services: blog_service
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**/*.xml